---
# tasks file for roles/python
- name: Install latest python3 and pip3
  become: yes
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes 

- name: Using pip3 as default pip 
  become: yes
  command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

- name: Using python3 as default python  
  become: yes
  command: echo "alias python='python3'" >> .bashrc && source .bashrc
