---
# tasks file for roles/ubuntu-install
  - name: Install java 
    apt:
      name: default-jre
      state: present 
      update_cache: yes

  - name: Install via ansible, boto, and openstack via pip
    pip: 
      name:
        - ansible
        - boto
        - python-openstackclient
