---
# tasks file for roles/setup-ubuntu
- name: Install httpd
  become: yes
  apt: 
    name: apache2
    state: latest
    update_cache: yes 

- name: Disable UFW
  service:
    name: ufw 
    state: stopped
    enabled: no

- name: allow UFW in apache2
  become: yes 
  ufw: 
    rule: allow
    port: '80'
    proto: tcp
    state: enabled

- name: Create directory for the website
  become: yes 
  file: 
    path: /var/www/quiz32
    state: directory
    owner: nobody
    group: nogroup

- name: Create index.html 
  become: yes
  copy: 
    content: "<h1> Quiz 3.2 Installing HTTPD Server 12/20/2020 <h1>" 
    dest: /var/www/quiz32/index.html

- name: config file
  become: yes 
  copy: 
    src: /etc/apache2/sites-available/000-default.conf
    remote_src: yes
    dest: /quiz32.conf

- name: Add config file
  become: yes 
  copy: 
    src: /quiz32.conf
    remote_src: yes
    dest: /etc/apache2/sites-available

- name: Edit config dir
  become: yes
  replace: 
    path: /etc/apache2/sites-available/quiz32.conf
    regexp: "#ServeName www.example.com" 
    replace: "#ServerName www.quiz32.com"

- name: Edit server admin
  become: yes
  replace: 
    path: /etc/apache2/sites-available/quiz32.conf 
    regexp: "ServerAdmin webmaster@localhost" 
    replace: "ServerAdmin quiz32@md.com"

- name: Activate virtualhost
  become: yes
  command: a2ensite quiz32.conf

- name: Test PHP
  become: yes 
  copy: 
    content: "<h1> Quiz 3.2 12/20/2020 </h1>"
    dest: /var/www/quiz32/info.php

- name: reload apache
  become: yes
  service: 
    name: apache2
    state: reloaded

